<div style="background-color:#9F149F; padding: 10px; height: 70px; border-radius: 15px;">
    <div style="font-family: 'Georgia', serif; font-size: 20px;color: white; padding: 10px; text-align: right; position: absolute; right: 20px;">
        Sakshi <br>
        <span style="font-family: 'Arial', sans-serif;font-size: 14px; color: white">Data Analytics Trainee | AI/ML bootcamp</span> 
    </div>
</div>

<div style="background-color: #400040 ; padding: 10px; text-align: center; color: white; font-size: 32px; font-family: 'Arial', sans-serif;">
    NumPy<br>
    <h3 style="text-align: center; color: white; font-size: 15px; font-family: 'Arial', sans-serif;">NumPy Library of Python</h3>
</div>


**NumPy, short for Numerical Python, is an open-source Python library primarily used for numerical and scientific computing. At its core, NumPy provides the ndarray, which stands for N-dimensional array.**

**The ndarray is a fast, efficient, multidimensional container of elements all of the same type (homogeneous). It allows storing and performing operations on large arrays and matrices, which are indexed by tuples of non-negative integers.**

- Numerical Python -> core library for scientific computing in Python.
- It provides:
  - Efficient array storage and operations
  - Fast mathematical functions
  - Useful tools -> random, linear algebra, fourier series transformation

<div style="background-color: #502989; color: white ; padding: 4px;">
    <h3>Check if pip is installed
</h3> </div> 

**pip --version**
 - PIP stands for "Pip Installs Packages" and is a package manager for Python.

 **Installing a packages:** pip install requests

 **Upgrading pip:** python -m pip install --upgrade pip

<div style="background-color:#502989 ; color: white; padding: 4px;">
    <h3>How to install numpy library?
</h3> </div> 

 - pip install numpy --> terminal


<div style="background-color:#502989; color: white; padding: 4px;">
    <h3>Importing NumPy
</h3> </div> 

 - To use NumPy, we need to import it into your Python code. The common convention is to import it as np:

In [1]:
#  import library 
import numpy as np  #as is alias

<div style="background-color: #502989; color: white; padding: 4px;">
    <h3>Verifying the Installation
</h3> </div> 

In [2]:

print(np.__version__) # checking numpy's version 

2.3.1


<div style="background-color: skyblue; color: black; padding: 4px;">
    <h3>NumPy Array
</h3> </div> 


**np.array()** is a function in the NumPy library that converts a Python list (or other array-like structure) into a NumPy ndarray (N-dimensional array) object.

**Advantages of NumPy Arrays**
 - **Performance:**  NumPy arrays are faster than Python lists for numerical operations.
 - **Memory Efficiency:** Arrays use less memory as they store elements of the same data type.
 - **Convenience:** NumPy provides built-in functions for complex operations, making code concise and readable.


<div style="background-color: skyblue; color: black; padding: 4px;">
    <h3>Why use numpy array instead of list
</h3> </div> 

**NumPy arrays are ideal for numerical computations due to their speed, efficiency, and rich functionality, while Python lists are more general-purpose and flexible for non-numerical tasks.**

In [103]:
l1 = [1,2,3,4,5,6]
arr1 = np.array(l1)

<div style="background-color: skyblue; color: black; padding: 4px;">
    <h3>Creating  1-D Array 
</h3> </div> 

In [3]:
#creates a NumPy array named arr1 from a Python list.
arr1 = np.array([1,2,3,4,5,6])
arr1


array([1, 2, 3, 4, 5, 6])

<div style="background-color: skyblue; color: black; padding: 4px;">
    <h3>Array Attributes
</h3> </div> 

**NumPy arrays have several important attributes:**

In [4]:
arr1[2]

np.int64(3)

In [5]:
print(arr1[1])

2


In [6]:
#check type of arr1
type(arr1) 

numpy.ndarray

In [7]:
 #total number of elements
arr1.size

6

In [8]:
#shape
arr1.shape 

(6,)

In [9]:
#check number of dimensions
arr1.ndim 

1

### 1-D Vs 2-D lists 

In [10]:

lists = [1,2,3,4,5]
list2 = [[1,2,3,4,5],[6,7,8,9,10]]
lists
#list



[1, 2, 3, 4, 5]

In [11]:
lists = [1,2,3,4,5]
list2 = [[1,2,3,4,5],[6,7,8,9,10]]
list2
#list2

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

<div style="background-color: skyblue; color: black; padding: 4px;">
    <h3>Creating  2-D Array 
</h3> </div> 

In [12]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])  #create aar2 
arr2 #print arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
arr2.size #size

8

In [14]:
arr2.ndim # number of dimensions

2

In [15]:
arr2.dtype #type

dtype('int64')

In [16]:
type(arr2)

numpy.ndarray

<div style="background-color: skyblue; color: black; padding: 4px;">
    <h3>Arrays for all zeros 
</h3> </div> 

In [17]:
# Array fo all 0's

np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.zeros(3)

array([0., 0., 0.])

In [19]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

<div style="background-color: skyblue; color: black; padding: 4px;">
    <h3>Arrays for all ones
</h3> </div> 

In [20]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

<div style="background-color: skyblue; color: black; padding: 4px;">
    <h3>Identity Matrix
</h3> </div> 

In [25]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [27]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<div style="background-color: skyblue; color: black; padding: 4px;">
    <h3>Full Array
</h3> </div> 

In [29]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

<div style="background-color: skyblue; color: black; padding: 4px;">
    <h3>Arrange
</h3> </div> 

In [30]:
# Create a array of evenly spaced intervals elements
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [31]:
np.arange(0,30,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [32]:
np.arange(0,50,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48])

<div style="background-color: skyblue; color: black; padding: 4px;">
    <h3>Using linspace
</h3> </div> 

In [33]:
# Create an array with values that are spaced linearly in a specified interval
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [34]:
np.linspace(0,1.5,10)

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        , 1.16666667, 1.33333333, 1.5       ])

In [35]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [36]:
np.linspace(0, 20, num=6)

array([ 0.,  4.,  8., 12., 16., 20.])

<div style="background-color: skyblue; color: black; padding: 4px;">
    <h3>Indexing and Slicing
</h3> </div> 

In [37]:
# Indexing and Slicing
arr3 = np.array([[10,20,30],[40,50,60]])
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [38]:
print(arr3[1,2])

60


In [39]:
print(arr3[:1])

[[10 20 30]]


In [40]:
print(arr3[1:])

[[40 50 60]]


In [41]:
arr3[arr3>20]

array([30, 40, 50, 60])

<div style="background-color: skyblue; color: black; padding: 4px;">
    <h3>Ascending & decending
</h3> </div> 

In [42]:
#create array
arr4=np.array([34,56,43,23,45,87,89])

In [43]:
#print aar4
arr4

array([34, 56, 43, 23, 45, 87, 89])

In [44]:
#ascending order
np.sort(arr4)             # default - ascending

array([23, 34, 43, 45, 56, 87, 89])

In [45]:
#decending order
#decending = np.sort(arr4,reverse=True)
#arr4

TypeError: sort() got an unexpected keyword argument 'reverse'

# Array Manipulation
# Reshape

In [46]:
# Array Manipulation
# Reshape
arr5 = np.arange(6)

In [47]:
arr5

array([0, 1, 2, 3, 4, 5])

In [52]:
arr5.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [53]:
arr4.reshape(2,5)   #giving value error because cannot reshape array of 6 

ValueError: cannot reshape array of size 7 into shape (2,5)

 - **Can you convert 1-D into 2-D arrays or vise-a-versa**

In [54]:
# Can you convert 1-D into 2-D arrays or vise-a-versa
arr6 = np.array([1,2,31,3,4,5])

In [55]:
arr6 #print arr6

array([ 1,  2, 31,  3,  4,  5])

In [56]:
arr6.reshape(3,2) #convert into 3-D

array([[ 1,  2],
       [31,  3],
       [ 4,  5]])

In [57]:
arr6.reshape(2,3) #Convert (reshape)

array([[ 1,  2, 31],
       [ 3,  4,  5]])

In [58]:
arr6.reshape(6,1) #reshape

array([[ 1],
       [ 2],
       [31],
       [ 3],
       [ 4],
       [ 5]])

### converting multiple arrays in single line

In [59]:
arr6.flatten() #converting multiple arrays in single line

array([ 1,  2, 31,  3,  4,  5])

<div style="background-color: skyblue; color: black; padding: 4px;">
    <h3>Concatenation
</h3> </div> 

In [60]:
arr7=[[1,2,3],[4,5,6]]   #create arr7
arr8=[[10,20,30],[40,50,60]]  #create arr8

In [61]:
# Concatenate
np.concatenate([arr7,arr8], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30],
       [40, 50, 60]])

In [62]:
arr8 #print

[[10, 20, 30], [40, 50, 60]]

In [63]:
arr7 #print arr7

[[1, 2, 3], [4, 5, 6]]

In [64]:
np.split(arr8, 2) # Check Documentation

AttributeError: 'list' object has no attribute 'shape'

<div style="background-color: skyblue; color: black; padding: 4px;">
    <h3>Basic Operations
</h3> </div> 

In [65]:
# sum of all array elements
arr0 = np.array([1,2,3,4,5,6,7,8,9])
print(np.sum(arr0))

45


In [66]:
np.mean(arr0)   # findmean of array
print(np.mean(arr0))

5.0


In [67]:
np.std(arr0)  # standard divation 
print(np.std(arr0))

2.581988897471611


In [68]:
np.min(arr0)    #find minimum value
print(np.min(arr0))

1


In [69]:
np.max(arr0) # find maximum value 
print(np.max(arr0))

9


**The np.cumsum() function in NumPy is used to compute the cumulative sum of array**

In [70]:
np.cumsum(arr0) # cumulative sum
print(np.cumsum(arr0))

[ 1  3  6 10 15 21 28 36 45]


In [71]:
np.exp(arr0)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [72]:
np.sqrt(arr0) 

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [73]:
arr6 = np.array([1,2,3,4,5,6])
arr7 = np.array([1,2,3,4,5,6])
arr6+arr7

array([ 2,  4,  6,  8, 10, 12])

In [74]:
np.add(arr6,arr7)

array([ 2,  4,  6,  8, 10, 12])

In [75]:
np.multiply(arr6,arr7)

array([ 1,  4,  9, 16, 25, 36])

In [76]:
np.sin(arr6)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ])

In [77]:
np.log(arr6)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947])

<div style="background-color: skyblue; color: black; padding: 4px;">
    <h3>Random NumPy Module
</h3> </div> 

In [78]:
# Random
np.random.seed(9)
random = np.random.rand(3,2)

In [98]:
random  #give random array elements

array([[9, 2],
       [9, 6],
       [2, 1]], dtype=int32)

In [99]:
random = np.random.randint(1,10,(3,2))

In [100]:
random

array([[9, 9],
       [9, 3],
       [7, 9]], dtype=int32)

In [101]:
arr6 = ([[1,2],[3,4]])

In [102]:
arr7 = ([[5,6],[7,8]])

<div style="background-color: skyblue; color: black; padding: 4px;">
    <h3> Linear Algebra
</h3> </div> 


**The NumPy Linear Algebra Library provides a robust set of tools for performing linear algebra operations efficiently. It relies on BLAS (Basic Linear Algebra Subprograms) and LAPACK (Linear Algebra Package) for optimized performance.**

In [92]:
# Linear Algebra
np.dot(arr6,arr7)  #matrix multiplication

array([[19, 22],
       [43, 50]])

In [93]:
np.linalg.inv(arr6)  #Compute inverse of a matrix

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [94]:
np.linalg.det(arr6) #Determinant

np.float64(-2.0000000000000004)

In [95]:
np.linalg.eig(arr6) #Compute eigenvalues and eigenvectors

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

In [96]:
import sys

lst = list(range(1000))
arr8 = np.arange(1000)
print(sys.getsizeof(lst))
print(arr8.nbytes)

8056
8000


In [97]:
arr8

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18